### ISSUE TITLE
When will the source code be released?

### ISSUE THREAD

**Issue by hyper-z** [ning-mz/SCA-GPS#1]
Hello, thank you for your wonderful paper. When will the source code be released?

**Comment by ning-mz** [comment]
Hello, sorry for the delay. The code has been released now. Please download the pytorch_model.bin of roberta-chn from huggingface  as the repo space is limited. Save the weight to "roberta" folder. Thank you. 

https://huggingface.co/hfl/chinese-roberta-wwm-ext/tree/main
