### ISSUE TITLE
Unable to resolve dependency issues

### ISSUE THREAD

**Issue by ArchitMukherjee** [ning-mz/SCA-GPS#2]
Hello, I am trying to replicate the results but am unable to resolve the python package dependency issues.

### My Device Information
I am running a docker container with the following specs:
**OS Version:** Ubuntu 18.04.5
**GPU:** Tesla T4 (x2)
**CUDA Version:** 11.1

In the docker container I have created a conda environment with **Python 3.8.13** and other versions.

But I am unable to resolve the issues with the packages specially the `allennlp`. I have tried multiple versions of Python but wasn't able to run it. Can you please specify the details of the environment or suggest a suitable docker image and if possible provide a requirements.txt file? 

If you have any other solution please let me know. Thankyou.

**Comment by ning-mz** [comment]
Hi, sorry for late reply. I'm using Python 3.7.9 with CUDA 10.1.243 in my conda environment. Currently I have DDLs to deal with I will give requirements later. You may try the requirements in GeoQA repo, as I developed this work based on GeoQA environment.
